from enum import Enum


class ErrorCode(str, Enum):
    AUTH_FAILED = "AUTH_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    RATE_LIMITED = "RATE_LIMITED"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_UNKNOWN = "ORDER_UNKNOWN"
    WS_DISCONNECTED = "WS_DISCONNECTED"
    WS_RESUBSCRIBE_FAILED = "WS_RESUBSCRIBE_FAILED"
    PROTOCOL_ERROR = "PROTOCOL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
